In [ ]:
import pandas as pd
import numpy as np
from scipy.stats import pearsonr

In [ ]:
data = [['Leon', 5,3,4,4,4,5,1,3,2,5,3,4,1,4,5,1,3,2,1  ], ['Chris', 3,1,2,3,3,1,3,2,5,3,3,1,2,3,3,1,3,2,5,3], ['Ethan', 4,3,4,1,5,1,2,3,4,5,4,3,4,2,5,1,2,3,4,5],['Miranda', 3,3,1,5,4,2,5,3,2,4,3,3,1,5,4,2,5,3,2,4],['Rose', 1,5,5,2,1,3,1,2,3,3,1,5,5,2,1,3,1,2,3,3]
        ,['Jihan', 4,5,1,3,2,3,1,2,3,3,4,5,1,3,2,3,1,2,3,3], ['Helmi', 3,1,2,3,3,1,2,3,4,5,3,1,2,3,3,1,2,3,4,5], ['Jundi', 4,3,4,3,5,2,5,3,2,4,4,3,5,2,5,2,5,3,2,4],['Rafi', 1,3,1,5,4,3,1,2,3,3,1,5,3,2,1,3,1,2,3,3],['Fikri', 1,5,5,2,1,4,5,1,3,2,1,5,5,2,1,4,5,1,3,2]
        ,['Diluc', 1,2,3,4,5,4,3,4,3,5,1,2,3,4,5,4,3,4,3,5], ['Jean', 3,1,2,3,3,2,5,3,2,4,3,1,2,3,3,2,5,3,2,4], ['Paimon', 4,3,4,3,5,3,3,1,5,4,4,3,4,3,5,3,3,1,5,4],['Raiden', 3,3,1,5,4,1,5,5,2,1,3,3,1,5,4,1,5,5,2,1],['Bennet', 1,5,5,2,1,4,3,4,3,5,1,5,5,2,1,4,3,4,3,5]
        ,['User16', 2,5,3,2,4,3,1,2,3,3,2,5,3,2,4,3,1,2,3,3], ['User17', 3,1,2,3,3,1,5,5,2,1,3,1,2,3,3,1,5,5,2,1], ['User18', 4,3,4,3,5,1,5,5,2,1,4,3,4,3,5,1,5,5,2,1],['User19', 3,3,1,5,4,3,2,4,3,1,3,3,1,5,4,3,2,4,3,1],['User20', 1,5,5,2,1,2,1,4,3,4,1,5,5,2,1,2,1,4,3,4]
        ]

# Create the pandas DataFrame
df = pd.DataFrame(data, columns = ['Name','Item1', 'Item2', 'Item3', 'Item4', 'Item5'
,'Item6', 'Item7', 'Item8', 'Item9', 'Item10'
,'Item11', 'Item12', 'Item13', 'Item14', 'Item15'
,'Item16', 'Item17', 'Item18', 'Item19', 'Item20'])
# print dataframe.
df = df.fillna(0)
df = df.astype({"Item1" : 'float', "Item2": 'float', "Item3": 'float', 'Item4': 'float', 'Item5': 'float'
,'Item6': 'float', 'Item7': 'float', 'Item8': 'float', 'Item9': 'float', 'Item10': 'float'
,'Item11': 'float', 'Item12': 'float', 'Item13': 'float', 'Item14': 'float', 'Item15': 'float'
,'Item16': 'float', 'Item17': 'float', 'Item18': 'float', 'Item19': 'float', 'Item20': 'float'})
df

,Name,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,...,Item11,Item12,Item13,Item14,Item15,Item16,Item17,Item18,Item19,Item20
0,Leon,5.0,3.0,4.0,4.0,4.0,5.0,1.0,3.0,2.0,...,3.0,4.0,1.0,4.0,5.0,1.0,3.0,2.0,1.0,0.0
1,Chris,3.0,1.0,2.0,3.0,3.0,1.0,3.0,2.0,5.0,...,3.0,1.0,2.0,3.0,3.0,1.0,3.0,2.0,5.0,3.0
2,Ethan,4.0,3.0,4.0,1.0,5.0,1.0,2.0,3.0,4.0,...,4.0,3.0,4.0,2.0,5.0,1.0,2.0,3.0,4.0,5.0
3,Miranda,3.0,3.0,1.0,5.0,4.0,2.0,5.0,3.0,2.0,...,3.0,3.0,1.0,5.0,4.0,2.0,5.0,3.0,2.0,4.0
4,Rose,1.0,5.0,5.0,2.0,1.0,3.0,1.0,2.0,3.0,...,1.0,5.0,5.0,2.0,1.0,3.0,1.0,2.0,3.0,3.0
5,Jihan,4.0,5.0,1.0,3.0,2.0,3.0,1.0,2.0,3.0,...,4.0,5.0,1.0,3.0,2.0,3.0,1.0,2.0,3.0,3.0
6,Helmi,3.0,1.0,2.0,3.0,3.0,1.0,2.0,3.0,4.0,...,3.0,1.0,2.0,3.0,3.0,1.0,2.0,3.0,4.0,5.0
7,Jundi,4.0,3.0,4.0,3.0,5.0,2.0,5.0,3.0,2.0,...,4.0,3.0,5.0,2.0,5.0,2.0,5.0,3.0,2.0,4.0
8,Rafi,1.0,3.0,1.0,5.0,4.0,3.0,1.0,2.0,3.0,...,1.0,5.0,3.0,2.0,1.0,3.0,1.0,2.0,3.0,3.0
9,Fikri,1.0,5.0,5.0,2.0,1.0,4.0,5.0,1.0,3.0,...,1.0,5.0,5.0,2.0,1.0,4.0,5.0,1.0,3.0,2.0
10,Diluc,1.0,2.0,3.0,4.0,5.0,4.0,3.0,4.0,3.0,...,1.0,2.0,3.0,4.0,5.0,4.0,3.0,4.0,3.0,5.0
11,Jean,3.0,1.0,2.0,3.0,3.0,2.0,5.0,3.0,2.0,...,3.0,1.0,2.0,3.0,3.0,2.0,5.0,3.0,2.0,4.0
12,Paimon,4.0,3.0,4.0,3.0,5.0,3.0,3.0,1.0,5.0,...,4.0,3.0,4.0,3.0,5.0,3.0,3.0,1.0,5.0,4.0
13,Raiden,3.0,3.0,1.0,5.0,4.0,1.0,5.0,5.0,2.0,...,3.0,3.0,1.0,5.0,4.0,1.0,5.0,5.0,2.0,1.0
14,Bennet,1.0,5.0,5.0,2.0,1.0,4.0,3.0,4.0,3.0,...,1.0,5.0,5.0,2.0,1.0,4.0,3.0,4.0,3.0,5.0
15,User16,2.0,5.0,3.0,2.0,4.0,3.0,1.0,2.0,3.0,...,2.0,5.0,3.0,2.0,4.0,3.0,1.0,2.0,3.0,3.0
16,User17,3.0,1.0,2.0,3.0,3.0,1.0,5.0,5.0,2.0,...,3.0,1.0,2.0,3.0,3.0,1.0,5.0,5.0,2.0,1.0
17,User18,4.0,3.0,4.0,3.0,5.0,1.0,5.0,5.0,2.0,...,4.0,3.0,4.0,3.0,5.0,1.0,5.0,5.0,2.0,1.0
18,User19,3.0,3.0,1.0,5.0,4.0,3.0,2.0,4.0,3.0,...,3.0,3.0,1.0,5.0,4.0,3.0,2.0,4.0,3.0,1.0
19,User20,1.0,5.0,5.0,2.0,1.0,2.0,1.0,4.0,3.0,...,1.0,5.0,5.0,2.0,1.0,2.0,1.0,4.0,3.0,4.0

In [ ]:
#mengambil nilai rerata dari tiap user
user_mean = df.iloc[:,:4].mean(axis=1)
print(user_mean)

0     4.000000
1     2.000000
2     3.666667
3     2.333333
4     3.666667
5     3.333333
6     2.000000
7     3.666667
8     1.666667
9     3.666667
10    2.000000
11    2.000000
12    3.666667
13    2.333333
14    3.666667
15    3.333333
16    2.000000
17    3.666667
18    2.333333
19    3.666667
dtype: float64

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.

In [ ]:
from scipy.stats import pearsonr
import numpy as np
arr = df.iloc[:, 1:5].to_numpy()
arr

array([[5., 3., 4., 4.],
       [3., 1., 2., 3.],
       [4., 3., 4., 1.],
       [3., 3., 1., 5.],
       [1., 5., 5., 2.],
       [4., 5., 1., 3.],
       [3., 1., 2., 3.],
       [4., 3., 4., 3.],
       [1., 3., 1., 5.],
       [1., 5., 5., 2.],
       [1., 2., 3., 4.],
       [3., 1., 2., 3.],
       [4., 3., 4., 3.],
       [3., 3., 1., 5.],
       [1., 5., 5., 2.],
       [2., 5., 3., 2.],
       [3., 1., 2., 3.],
       [4., 3., 4., 3.],
       [3., 3., 1., 5.],
       [1., 5., 5., 2.]])

In [ ]:
from scipy.stats import pearsonr
sim_matrix = [np.NaN]
for i in arr[1:]:
  r, p = pearsonr(arr[0], i)
  sim_matrix.append(r)
sim_matrix

[nan,
 0.8528028654224415,
 0.2886751345948129,
 0.0,
 -0.7921180343813393,
 -0.2390457218668787,
 0.8528028654224415,
 0.7071067811865475,
 -0.42640143271122083,
 -0.7921180343813393,
 -0.31622776601683794,
 0.8528028654224415,
 0.7071067811865475,
 0.0,
 -0.7921180343813393,
 -0.8660254037844388,
 0.8528028654224415,
 0.7071067811865475,
 0.0,
 -0.7921180343813393]

In [ ]:
df['Similarity'] = sim_matrix
df

,Name,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,...,Item12,Item13,Item14,Item15,Item16,Item17,Item18,Item19,Item20,Similarity
0,Leon,5.0,3.0,4.0,4.0,4.0,5.0,1.0,3.0,2.0,...,4.0,1.0,4.0,5.0,1.0,3.0,2.0,1.0,0.0,NaN
1,Chris,3.0,1.0,2.0,3.0,3.0,1.0,3.0,2.0,5.0,...,1.0,2.0,3.0,3.0,1.0,3.0,2.0,5.0,3.0,0.852803
2,Ethan,4.0,3.0,4.0,1.0,5.0,1.0,2.0,3.0,4.0,...,3.0,4.0,2.0,5.0,1.0,2.0,3.0,4.0,5.0,0.288675
3,Miranda,3.0,3.0,1.0,5.0,4.0,2.0,5.0,3.0,2.0,...,3.0,1.0,5.0,4.0,2.0,5.0,3.0,2.0,4.0,0.000000
4,Rose,1.0,5.0,5.0,2.0,1.0,3.0,1.0,2.0,3.0,...,5.0,5.0,2.0,1.0,3.0,1.0,2.0,3.0,3.0,-0.792118
5,Jihan,4.0,5.0,1.0,3.0,2.0,3.0,1.0,2.0,3.0,...,5.0,1.0,3.0,2.0,3.0,1.0,2.0,3.0,3.0,-0.239046
6,Helmi,3.0,1.0,2.0,3.0,3.0,1.0,2.0,3.0,4.0,...,1.0,2.0,3.0,3.0,1.0,2.0,3.0,4.0,5.0,0.852803
7,Jundi,4.0,3.0,4.0,3.0,5.0,2.0,5.0,3.0,2.0,...,3.0,5.0,2.0,5.0,2.0,5.0,3.0,2.0,4.0,0.707107
8,Rafi,1.0,3.0,1.0,5.0,4.0,3.0,1.0,2.0,3.0,...,5.0,3.0,2.0,1.0,3.0,1.0,2.0,3.0,3.0,-0.426401
9,Fikri,1.0,5.0,5.0,2.0,1.0,4.0,5.0,1.0,3.0,...,5.0,5.0,2.0,1.0,4.0,5.0,1.0,3.0,2.0,-0.792118
10,Diluc,1.0,2.0,3.0,4.0,5.0,4.0,3.0,4.0,3.0,...,2.0,3.0,4.0,5.0,4.0,3.0,4.0,3.0,5.0,-0.316228
11,Jean,3.0,1.0,2.0,3.0,3.0,2.0,5.0,3.0,2.0,...,1.0,2.0,3.0,3.0,2.0,5.0,3.0,2.0,4.0,0.852803
12,Paimon,4.0,3.0,4.0,3.0,5.0,3.0,3.0,1.0,5.0,...,3.0,4.0,3.0,5.0,3.0,3.0,1.0,5.0,4.0,0.707107
13,Raiden,3.0,3.0,1.0,5.0,4.0,1.0,5.0,5.0,2.0,...,3.0,1.0,5.0,4.0,1.0,5.0,5.0,2.0,1.0,0.000000
14,Bennet,1.0,5.0,5.0,2.0,1.0,4.0,3.0,4.0,3.0,...,5.0,5.0,2.0,1.0,4.0,3.0,4.0,3.0,5.0,-0.792118
15,User16,2.0,5.0,3.0,2.0,4.0,3.0,1.0,2.0,3.0,...,5.0,3.0,2.0,4.0,3.0,1.0,2.0,3.0,3.0,-0.866025
16,User17,3.0,1.0,2.0,3.0,3.0,1.0,5.0,5.0,2.0,...,1.0,2.0,3.0,3.0,1.0,5.0,5.0,2.0,1.0,0.852803
17,User18,4.0,3.0,4.0,3.0,5.0,1.0,5.0,5.0,2.0,...,3.0,4.0,3.0,5.0,1.0,5.0,5.0,2.0,1.0,0.707107
18,User19,3.0,3.0,1.0,5.0,4.0,3.0,2.0,4.0,3.0,...,3.0,1.0,5.0,4.0,3.0,2.0,4.0,3.0,1.0,0.000000
19,User20,1.0,5.0,5.0,2.0,1.0,2.0,1.0,4.0,3.0,...,5.0,5.0,2.0,1.0,2.0,1.0,4.0,3.0,4.0,-0.792118

In [ ]:
def make_prediction(a, b1, b2):
  ra = sum(a[0:19])/len(a[0:19])
  rb1 = sum(b1[0:20])/len(b1[0:20])
  rb2 = sum(b2[0:20])/len(b2[0:20])
  sim_ab1 = b1[18]
  sim_ab2 = b2[18]
  rb1p = b1[17]
  rb2p = b2[17]

  return ra + 1/(sim_ab1 + sim_ab2) * (sim_ab1 * (rb1p - rb1) + sim_ab2 * (rb2p - rb2 ))

In [ ]:
arr = df.iloc[:, 1:20].to_numpy()

Leon = arr[0]
Chris = arr[1]
Ethan = arr[2]
Miranda = arr[3]
Rose = arr[4]
Jihan = arr[5]
Helmi = arr[6]
Jundi = arr[7]
Rafi  = arr[8]
Fikri = arr[9]
Diluc = arr[10]
Jean = arr[11]
Paimon = arr[12]
Raiden = arr[13]
Bennet = arr[14]
User16 = arr[15]
User17 = arr[16]
User18 = arr[17]
User19 = arr[18]
User20 = arr[19]

df['Item20'][0] = make_prediction(Leon, Chris, Ethan)
#Miranda,Rose,Jihan,Helmi,Jundi,Rafi,Fikri,Diluc,Jean,Paimon,Raiden,Bennet,User16,User17,User18,User19,User20

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
df

,Name,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,...,Item12,Item13,Item14,Item15,Item16,Item17,Item18,Item19,Item20,Similarity
0,Leon,5.0,3.0,4.0,4.0,4.0,5.0,1.0,3.0,2.0,...,4.0,1.0,4.0,5.0,1.0,3.0,2.0,1.0,2.766082,NaN
1,Chris,3.0,1.0,2.0,3.0,3.0,1.0,3.0,2.0,5.0,...,1.0,2.0,3.0,3.0,1.0,3.0,2.0,5.0,3.000000,0.852803
2,Ethan,4.0,3.0,4.0,1.0,5.0,1.0,2.0,3.0,4.0,...,3.0,4.0,2.0,5.0,1.0,2.0,3.0,4.0,5.000000,0.288675
3,Miranda,3.0,3.0,1.0,5.0,4.0,2.0,5.0,3.0,2.0,...,3.0,1.0,5.0,4.0,2.0,5.0,3.0,2.0,4.000000,0.000000
4,Rose,1.0,5.0,5.0,2.0,1.0,3.0,1.0,2.0,3.0,...,5.0,5.0,2.0,1.0,3.0,1.0,2.0,3.0,3.000000,-0.792118
5,Jihan,4.0,5.0,1.0,3.0,2.0,3.0,1.0,2.0,3.0,...,5.0,1.0,3.0,2.0,3.0,1.0,2.0,3.0,3.000000,-0.239046
6,Helmi,3.0,1.0,2.0,3.0,3.0,1.0,2.0,3.0,4.0,...,1.0,2.0,3.0,3.0,1.0,2.0,3.0,4.0,5.000000,0.852803
7,Jundi,4.0,3.0,4.0,3.0,5.0,2.0,5.0,3.0,2.0,...,3.0,5.0,2.0,5.0,2.0,5.0,3.0,2.0,4.000000,0.707107
8,Rafi,1.0,3.0,1.0,5.0,4.0,3.0,1.0,2.0,3.0,...,5.0,3.0,2.0,1.0,3.0,1.0,2.0,3.0,3.000000,-0.426401
9,Fikri,1.0,5.0,5.0,2.0,1.0,4.0,5.0,1.0,3.0,...,5.0,5.0,2.0,1.0,4.0,5.0,1.0,3.0,2.000000,-0.792118
10,Diluc,1.0,2.0,3.0,4.0,5.0,4.0,3.0,4.0,3.0,...,2.0,3.0,4.0,5.0,4.0,3.0,4.0,3.0,5.000000,-0.316228
11,Jean,3.0,1.0,2.0,3.0,3.0,2.0,5.0,3.0,2.0,...,1.0,2.0,3.0,3.0,2.0,5.0,3.0,2.0,4.000000,0.852803
12,Paimon,4.0,3.0,4.0,3.0,5.0,3.0,3.0,1.0,5.0,...,3.0,4.0,3.0,5.0,3.0,3.0,1.0,5.0,4.000000,0.707107
13,Raiden,3.0,3.0,1.0,5.0,4.0,1.0,5.0,5.0,2.0,...,3.0,1.0,5.0,4.0,1.0,5.0,5.0,2.0,1.000000,0.000000
14,Bennet,1.0,5.0,5.0,2.0,1.0,4.0,3.0,4.0,3.0,...,5.0,5.0,2.0,1.0,4.0,3.0,4.0,3.0,5.000000,-0.792118
15,User16,2.0,5.0,3.0,2.0,4.0,3.0,1.0,2.0,3.0,...,5.0,3.0,2.0,4.0,3.0,1.0,2.0,3.0,3.000000,-0.866025
16,User17,3.0,1.0,2.0,3.0,3.0,1.0,5.0,5.0,2.0,...,1.0,2.0,3.0,3.0,1.0,5.0,5.0,2.0,1.000000,0.852803
17,User18,4.0,3.0,4.0,3.0,5.0,1.0,5.0,5.0,2.0,...,3.0,4.0,3.0,5.0,1.0,5.0,5.0,2.0,1.000000,0.707107
18,User19,3.0,3.0,1.0,5.0,4.0,3.0,2.0,4.0,3.0,...,3.0,1.0,5.0,4.0,3.0,2.0,4.0,3.0,1.000000,0.000000
19,User20,1.0,5.0,5.0,2.0,1.0,2.0,1.0,4.0,3.0,...,5.0,5.0,2.0,1.0,2.0,1.0,4.0,3.0,4.000000,-0.792118